import React from 'react';

interface LegalModalProps {
  type: 'privacy' | 'terms';
  onClose: () => void;
  language?: string;
}

const LEGAL_TEXTS: Record<string, any> = {
  es: {
    privacy: { title: "Política de Privacidad", updated: "Última actualización: 14 de Marzo de 2026", intro: "En bdai, respetamos su privacidad y estamos comprometidos a proteger sus datos personales.", s1title: "1. Información que recopilamos", s1: "Recopilamos datos que usted nos proporciona directamente: nombre, email, edad, ciudad, país e idioma. También recopilamos datos de ubicación GPS cuando usa la app para desbloquear paradas y ganar millas.", s2title: "2. Cómo usamos su información", s2: "Utilizamos su información para proporcionar y mejorar nuestros servicios, personalizar su experiencia y gestionar su cuenta.", s3title: "3. Compartir su información", s3: "No vendemos sus datos personales a terceros. Podemos compartir información anonimizada con ayuntamientos y comercios locales para mejorar la experiencia turística.", s4title: "4. Sus derechos (RGPD)", s4: "Tiene derecho a acceder, rectificar y solicitar la eliminación de sus datos. Puede ejercer su derecho al olvido eliminando su cuenta desde el perfil.", s5title: "5. Contacto", s5: "Daysi Chong Zambrano — NIF: 16648955Z — Calle Calvo Sotelo 34, Logroño, La Rioja 26003 — info@bdai.travel" },
    terms: { title: "Términos de Uso", updated: "Última actualización: 14 de Marzo de 2026", intro: "Bienvenido a bdai. Al acceder o utilizar nuestra aplicación, usted acepta estos Términos de Uso.", s1title: "1. Uso de la Aplicación", s1: "bdai es un ecosistema de datos turísticos y gamificación. Usted se compromete a utilizar la app solo para fines legales.", s2title: "2. Cuentas de Usuario", s2: "Para acceder a ciertas funciones, debe crear una cuenta. Usted es responsable de mantener la confidencialidad de su información de inicio de sesión.", s3title: "3. Contenido Generado por el Usuario", s3: "Al aportar contenido a la comunidad, nos otorga una licencia no exclusiva y mundial para utilizarlo y mejorarlo.", s4title: "4. Gamificación y Recompensas", s4: "Las millas no tienen valor monetario real. Nos reservamos el derecho de modificar el programa de recompensas en cualquier momento.", s5title: "5. Limitación de Responsabilidad", s5: "La app se proporciona tal cual. No garantizamos que sea ininterrumpida o libre de errores.", s6title: "6. Contacto", s6: "Daysi Chong Zambrano — NIF: 16648955Z — Calle Calvo Sotelo 34, Logroño, La Rioja 26003 — info@bdai.travel" }
  },
  en: {
    privacy: { title: "Privacy Policy", updated: "Last updated: March 14, 2026", intro: "At bdai, we respect your privacy and are committed to protecting your personal data.", s1title: "1. Information We Collect", s1: "We collect data you provide directly: name, email, age, city, country and language. We also collect GPS location data when you use the app to unlock stops and earn miles.", s2title: "2. How We Use Your Information", s2: "We use your information to provide and improve our services, personalize your experience and manage your account.", s3title: "3. Sharing Your Information", s3: "We do not sell your personal data to third parties. We may share anonymized information with local governments and businesses to improve the tourism experience.", s4title: "4. Your Rights (GDPR)", s4: "You have the right to access, rectify and request deletion of your data. You can delete your account from the profile section.", s5title: "5. Contact", s5: "Daysi Chong Zambrano — NIF: 16648955Z — Calle Calvo Sotelo 34, Logroño, La Rioja 26003 — info@bdai.travel" },
    terms: { title: "Terms of Use", updated: "Last updated: March 14, 2026", intro: "Welcome to bdai. By accessing or using our application, you agree to these Terms of Use.", s1title: "1. Use of the Application", s1: "bdai is a tourism data and gamification ecosystem. You agree to use the app only for lawful purposes.", s2title: "2. User Accounts", s2: "To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your login information.", s3title: "3. User Generated Content", s3: "By contributing content to the community, you grant us a non-exclusive worldwide license to use and improve it.", s4title: "4. Gamification and Rewards", s4: "Miles have no real monetary value. We reserve the right to modify the rewards program at any time.", s5title: "5. Limitation of Liability", s5: "The app is provided as is. We do not guarantee that the app will be uninterrupted or error-free.", s6title: "6. Contact", s6: "Daysi Chong Zambrano — NIF: 16648955Z — Calle Calvo Sotelo 34, Logroño, La Rioja 26003 — info@bdai.travel" }
  },
  fr: {
    privacy: { title: "Politique de Confidentialité", updated: "Dernière mise à jour: 14 mars 2026", intro: "Chez bdai, nous respectons votre vie privée et nous nous engageons à protéger vos données personnelles.", s1title: "1. Informations collectées", s1: "Nous collectons les données que vous nous fournissez: nom, email, âge, ville, pays et langue. Nous collectons également des données de localisation GPS.", s2title: "2. Utilisation de vos données", s2: "Nous utilisons vos informations pour fournir et améliorer nos services, personnaliser votre expérience et gérer votre compte.", s3title: "3. Partage des données", s3: "Nous ne vendons pas vos données personnelles à des tiers.", s4title: "4. Vos droits (RGPD)", s4: "Vous avez le droit d'accéder, rectifier et demander la suppression de vos données.", s5title: "5. Contact", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Conditions d'Utilisation", updated: "Dernière mise à jour: 14 mars 2026", intro: "Bienvenue sur bdai. En accédant à notre application, vous acceptez ces Conditions.", s1title: "1. Utilisation", s1: "Vous vous engagez à utiliser l'application uniquement à des fins légales.", s2title: "2. Comptes", s2: "Vous êtes responsable de la confidentialité de vos informations de connexion.", s3title: "3. Contenu", s3: "En contribuant du contenu, vous nous accordez une licence mondiale non exclusive.", s4title: "4. Récompenses", s4: "Les miles n'ont pas de valeur monétaire réelle.", s5title: "5. Contact", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  de: {
    privacy: { title: "Datenschutzrichtlinie", updated: "Letzte Aktualisierung: 14. März 2026", intro: "Bei bdai respektieren wir Ihre Privatsphäre und verpflichten uns zum Schutz Ihrer persönlichen Daten.", s1title: "1. Gesammelte Daten", s1: "Wir sammeln Daten, die Sie uns direkt zur Verfügung stellen: Name, E-Mail, Alter, Stadt, Land und Sprache. Wir sammeln auch GPS-Standortdaten.", s2title: "2. Verwendung Ihrer Daten", s2: "Wir verwenden Ihre Informationen, um unsere Dienste bereitzustellen und Ihre Erfahrung zu personalisieren.", s3title: "3. Datenweitergabe", s3: "Wir verkaufen Ihre persönlichen Daten nicht an Dritte.", s4title: "4. Ihre Rechte (DSGVO)", s4: "Sie haben das Recht auf Zugang, Berichtigung und Löschung Ihrer Daten.", s5title: "5. Kontakt", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Nutzungsbedingungen", updated: "Letzte Aktualisierung: 14. März 2026", intro: "Willkommen bei bdai. Durch die Nutzung unserer App stimmen Sie diesen Nutzungsbedingungen zu.", s1title: "1. Nutzung", s1: "Sie verpflichten sich, die App nur für legale Zwecke zu nutzen.", s2title: "2. Benutzerkonten", s2: "Sie sind für die Vertraulichkeit Ihrer Anmeldedaten verantwortlich.", s3title: "3. Inhalte", s3: "Durch das Einreichen von Inhalten gewähren Sie uns eine weltweite nicht-exklusive Lizenz.", s4title: "4. Belohnungen", s4: "Meilen haben keinen echten Geldwert.", s5title: "5. Kontakt", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  it: {
    privacy: { title: "Informativa sulla Privacy", updated: "Ultimo aggiornamento: 14 marzo 2026", intro: "In bdai, rispettiamo la tua privacy e ci impegniamo a proteggere i tuoi dati personali.", s1title: "1. Dati raccolti", s1: "Raccogliamo i dati che ci fornisci: nome, email, età, città, paese e lingua. Raccogliamo anche dati GPS.", s2title: "2. Uso dei dati", s2: "Usiamo i tuoi dati per fornire e migliorare i nostri servizi.", s3title: "3. Condivisione", s3: "Non vendiamo i tuoi dati personali a terzi.", s4title: "4. I tuoi diritti (GDPR)", s4: "Hai il diritto di accedere, rettificare e richiedere la cancellazione dei tuoi dati.", s5title: "5. Contatto", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Termini di Utilizzo", updated: "Ultimo aggiornamento: 14 marzo 2026", intro: "Benvenuto su bdai. Accedendo all'app, accetti questi Termini.", s1title: "1. Uso", s1: "Ti impegni a usare l'app solo per scopi legali.", s2title: "2. Account", s2: "Sei responsabile della riservatezza delle tue credenziali.", s3title: "3. Contenuti", s3: "Contribuendo contenuti, ci concedi una licenza mondiale non esclusiva.", s4title: "4. Premi", s4: "Le miglia non hanno valore monetario reale.", s5title: "5. Contatto", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  pt: {
    privacy: { title: "Política de Privacidade", updated: "Última atualização: 14 de março de 2026", intro: "Na bdai, respeitamos a sua privacidade e comprometemo-nos a proteger os seus dados pessoais.", s1title: "1. Dados coletados", s1: "Coletamos os dados que você nos fornece: nome, email, idade, cidade, país e idioma. Coletamos também dados GPS.", s2title: "2. Uso dos dados", s2: "Usamos seus dados para fornecer e melhorar nossos serviços.", s3title: "3. Compartilhamento", s3: "Não vendemos seus dados pessoais a terceiros.", s4title: "4. Seus direitos (RGPD)", s4: "Você tem o direito de acessar, retificar e solicitar a exclusão dos seus dados.", s5title: "5. Contato", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Termos de Uso", updated: "Última atualização: 14 de março de 2026", intro: "Bem-vindo ao bdai. Ao acessar nosso app, você concorda com estes Termos.", s1title: "1. Uso", s1: "Você concorda em usar o app apenas para fins legais.", s2title: "2. Contas", s2: "Você é responsável pela confidencialidade das suas credenciais.", s3title: "3. Conteúdo", s3: "Ao contribuir com conteúdo, você nos concede uma licença mundial não exclusiva.", s4title: "4. Recompensas", s4: "As milhas não têm valor monetário real.", s5title: "5. Contato", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  ro: {
    privacy: { title: "Politica de Confidențialitate", updated: "Ultima actualizare: 14 martie 2026", intro: "La bdai, respectăm confidențialitatea dvs. și ne angajăm să vă protejăm datele personale.", s1title: "1. Date colectate", s1: "Colectăm datele pe care ni le furnizați direct: nume, email, vârstă, oraș, țară și limbă. Colectăm și date GPS.", s2title: "2. Utilizarea datelor", s2: "Folosim datele dvs. pentru a furniza și îmbunătăți serviciile noastre.", s3title: "3. Partajarea datelor", s3: "Nu vindem datele dvs. personale către terți.", s4title: "4. Drepturile dvs. (GDPR)", s4: "Aveți dreptul de a accesa, rectifica și solicita ștergerea datelor dvs.", s5title: "5. Contact", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Termeni de Utilizare", updated: "Ultima actualizare: 14 martie 2026", intro: "Bun venit la bdai. Accesând aplicația noastră, acceptați acești Termeni.", s1title: "1. Utilizare", s1: "Vă angajați să utilizați aplicația doar în scopuri legale.", s2title: "2. Conturi", s2: "Sunteți responsabil pentru confidențialitatea credențialelor dvs.", s3title: "3. Conținut", s3: "Contribuind cu conținut, ne acordați o licență mondială neexclusivă.", s4title: "4. Recompense", s4: "Milele nu au valoare monetară reală.", s5title: "5. Contact", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  ru: {
    privacy: { title: "Политика конфиденциальности", updated: "Последнее обновление: 14 марта 2026 г.", intro: "В bdai мы уважаем вашу конфиденциальность и обязуемся защищать ваши персональные данные.", s1title: "1. Собираемые данные", s1: "Мы собираем данные, которые вы предоставляете: имя, email, возраст, город, страна и язык. Также собираем GPS-данные.", s2title: "2. Использование данных", s2: "Мы используем ваши данные для предоставления и улучшения наших услуг.", s3title: "3. Передача данных", s3: "Мы не продаём ваши данные третьим лицам.", s4title: "4. Ваши права (GDPR)", s4: "Вы имеете право на доступ, исправление и удаление ваших данных.", s5title: "5. Контакт", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Условия использования", updated: "Последнее обновление: 14 марта 2026 г.", intro: "Добро пожаловать в bdai. Используя приложение, вы соглашаетесь с этими условиями.", s1title: "1. Использование", s1: "Вы обязуетесь использовать приложение только в законных целях.", s2title: "2. Аккаунты", s2: "Вы несёте ответственность за конфиденциальность своих данных.", s3title: "3. Контент", s3: "Предоставляя контент, вы даёте нам неисключительную мировую лицензию.", s4title: "4. Награды", s4: "Мили не имеют денежной ценности.", s5title: "5. Контакт", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  zh: {
    privacy: { title: "隐私政策", updated: "最后更新：2026年3月14日", intro: "在bdai，我们尊重您的隐私并致力于保护您的个人数据。", s1title: "1. 收集的数据", s1: "我们收集您直接提供的数据：姓名、电子邮件、年龄、城市、国家和语言。我们也收集GPS数据。", s2title: "2. 数据使用", s2: "我们使用您的数据提供和改进服务。", s3title: "3. 数据共享", s3: "我们不向第三方出售您的个人数据。", s4title: "4. 您的权利（GDPR）", s4: "您有权访问、更正和请求删除您的数据。", s5title: "5. 联系方式", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "使用条款", updated: "最后更新：2026年3月14日", intro: "欢迎使用bdai。使用我们的应用即表示您同意这些使用条款。", s1title: "1. 使用", s1: "您同意仅将本应用用于合法目的。", s2title: "2. 账户", s2: "您负责保护您的登录信息。", s3title: "3. 内容", s3: "提供内容即表示您授予我们非独占全球许可。", s4title: "4. 奖励", s4: "里程没有实际货币价值。", s5title: "5. 联系方式", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  ja: {
    privacy: { title: "プライバシーポリシー", updated: "最終更新日：2026年3月14日", intro: "bdaiではお客様のプライバシーを尊重し、個人データの保護に取り組んでいます。", s1title: "1. 収集するデータ", s1: "名前、メール、年齢、都市、国、言語などの情報を収集します。GPS データも収集します。", s2title: "2. データの使用", s2: "サービスの提供・改善のためにデータを使用します。", s3title: "3. データの共有", s3: "第三者への販売はしません。", s4title: "4. お客様の権利（GDPR）", s4: "データへのアクセス、修正、削除を要求する権利があります。", s5title: "5. お問い合わせ", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "利用規約", updated: "最終更新日：2026年3月14日", intro: "bdaiへようこそ。アプリを使用することで、この利用規約に同意したものとみなします。", s1title: "1. 利用", s1: "合法的な目的にのみアプリを使用。", s2title: "2. アカウント", s2: "ログイン情報の保護はお客様の責任です。", s3title: "3. コンテンツ", s3: "コンテンツを提供することで、非独占的な世界規模のライセンスを付与します。", s4title: "4. 報酬", s4: "マイルに金銭的価値はありません。", s5title: "5. お問い合わせ", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  ar: {
    privacy: { title: "سياسة الخصوصية", updated: "آخر تحديث: 14 مارس 2026", intro: "في bdai، نحترم خصوصيتك ونلتزم بحماية بياناتك الشخصية.", s1title: "1. البيانات التي نجمعها", s1: "نجمع البيانات التي تقدمها مباشرة: الاسم والبريد والعمر والمدينة والبلد واللغة. نجمع أيضاً بيانات GPS.", s2title: "2. استخدام البيانات", s2: "نستخدم بياناتك لتقديم خدماتنا وتحسينها.", s3title: "3. مشاركة البيانات", s3: "لا نبيع بياناتك الشخصية لأطراف ثالثة.", s4title: "4. حقوقك (GDPR)", s4: "لديك الحق في الوصول إلى بياناتك وتصحيحها وطلب حذفها.", s5title: "5. التواصل", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "شروط الاستخدام", updated: "آخر تحديث: 14 مارس 2026", intro: "مرحباً بك في bdai. باستخدام التطبيق، فإنك توافق على هذه الشروط.", s1title: "1. الاستخدام", s1: "تلتزم باستخدام التطبيق للأغراض القانونية فقط.", s2title: "2. الحسابات", s2: "أنت مسؤول عن سرية معلومات تسجيل الدخول الخاصة بك.", s3title: "3. المحتوى", s3: "بتقديم المحتوى، تمنحنا ترخيصاً غير حصري على مستوى العالم.", s4title: "4. المكافآت", s4: "الأميال ليس لها قيمة نقدية حقيقية.", s5title: "5. التواصل", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  hi: {
    privacy: { title: "गोपनीयता नीति", updated: "अंतिम अपडेट: 14 मार्च 2026", intro: "bdai में, हम आपकी गोपनीयता का सम्मान करते हैं और आपके व्यक्तिगत डेटा की सुरक्षा के लिए प्रतिबद्ध हैं।", s1title: "1. एकत्र किया गया डेटा", s1: "हम आपके द्वारा प्रदान किया गया डेटा एकत्र करते हैं: नाम, ईमेल, आयु, शहर, देश और भाषा। हम GPS डेटा भी एकत्र करते हैं।", s2title: "2. डेटा का उपयोग", s2: "हम आपके डेटा का उपयोग सेवाएं प्रदान करने और बेहतर बनाने के लिए करते हैं।", s3title: "3. डेटा साझा करना", s3: "हम आपका व्यक्तिगत डेटा तीसरे पक्ष को नहीं बेचते।", s4title: "4. आपके अधिकार (GDPR)", s4: "आपको अपने डेटा तक पहुंचने, सुधारने और हटाने का अधिकार है।", s5title: "5. संपर्क", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "उपयोग की शर्तें", updated: "अंतिम अपडेट: 14 मार्च 2026", intro: "bdai में आपका स्वागत है। ऐप का उपयोग करके, आप इन शर्तों से सहमत होते हैं।", s1title: "1. उपयोग", s1: "आप केवल कानूनी उद्देश्यों के लिए ऐप का उपयोग करने का वचन देते हैं।", s2title: "2. खाते", s2: "आप अपनी लॉगिन जानकारी की गोपनीयता के लिए जिम्मेदार हैं।", s3title: "3. सामग्री", s3: "सामग्री योगदान करके, आप हमें एक गैर-अनन्य वैश्विक लाइसेंस प्रदान करते हैं।", s4title: "4. पुरस्कार", s4: "मील का कोई वास्तविक मौद्रिक मूल्य नहीं है।", s5title: "5. संपर्क", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  ko: {
    privacy: { title: "개인정보 처리방침", updated: "최종 업데이트: 2026년 3월 14일", intro: "bdai에서는 귀하의 개인정보를 존중하며 보호하기 위해 최선을 다합니다.", s1title: "1. 수집하는 데이터", s1: "이름, 이메일, 나이, 도시, 국가, 언어 등 직접 제공하는 데이터를 수집합니다. GPS 데이터도 수집합니다.", s2title: "2. 데이터 사용", s2: "서비스 제공 및 개선을 위해 데이터를 사용합니다.", s3title: "3. 데이터 공유", s3: "개인 데이터를 제3자에게 판매하지 않습니다.", s4title: "4. 귀하의 권리 (GDPR)", s4: "데이터에 접근, 수정, 삭제를 요청할 권리가 있습니다.", s5title: "5. 연락처", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "이용약관", updated: "최종 업데이트: 2026년 3월 14일", intro: "bdai에 오신 것을 환영합니다. 앱을 사용함으로써 이 약관에 동의하게 됩니다.", s1title: "1. 사용", s1: "합법적인 목적으로만 앱을 사용하기로 동의합니다.", s2title: "2. 계정", s2: "로그인 정보의 기밀을 유지할 책임이 있습니다.", s3title: "3. 콘텐츠", s3: "콘텐츠를 제공함으로써 비독점적 글로벌 라이선스를 부여합니다.", s4title: "4. 보상", s4: "마일은 실제 금전적 가치가 없습니다.", s5title: "5. 연락처", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  tr: {
    privacy: { title: "Gizlilik Politikası", updated: "Son güncelleme: 14 Mart 2026", intro: "bdai'de gizliliğinize saygı duyuyor ve kişisel verilerinizi korumaya kararlıyız.", s1title: "1. Toplanan veriler", s1: "Doğrudan sağladığınız verileri topluyoruz: ad, e-posta, yaş, şehir, ülke ve dil. GPS verileri de toplanır.", s2title: "2. Verilerin kullanımı", s2: "Verilerinizi hizmetlerimizi sunmak ve iyileştirmek için kullanırız.", s3title: "3. Veri paylaşımı", s3: "Kişisel verilerinizi üçüncü şahıslara satmıyoruz.", s4title: "4. Haklarınız (GDPR)", s4: "Verilerinize erişme, düzeltme ve silme talep etme hakkınız vardır.", s5title: "5. İletişim", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Kullanım Koşulları", updated: "Son güncelleme: 14 Mart 2026", intro: "bdai'ye hoş geldiniz. Uygulamayı kullanarak bu koşulları kabul etmiş olursunuz.", s1title: "1. Kullanım", s1: "Uygulamayı yalnızca yasal amaçlar için kullanmayı taahhüt edersiniz.", s2title: "2. Hesaplar", s2: "Giriş bilgilerinizin gizliliğinden siz sorumlusunuz.", s3title: "3. İçerik", s3: "İçerik katkısında bulunarak bize münhasır olmayan dünya genelinde lisans vermiş olursunuz.", s4title: "4. Ödüller", s4: "Millerin gerçek parasal değeri yoktur.", s5title: "5. İletişim", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  nl: {
    privacy: { title: "Privacybeleid", updated: "Laatste update: 14 maart 2026", intro: "Bij bdai respecteren we uw privacy en zetten we ons in voor de bescherming van uw persoonsgegevens.", s1title: "1. Verzamelde gegevens", s1: "We verzamelen gegevens die u rechtstreeks verstrekt: naam, e-mail, leeftijd, stad, land en taal. We verzamelen ook GPS-gegevens.", s2title: "2. Gebruik van gegevens", s2: "We gebruiken uw gegevens om onze diensten te leveren en te verbeteren.", s3title: "3. Gegevens delen", s3: "We verkopen uw persoonsgegevens niet aan derden.", s4title: "4. Uw rechten (AVG)", s4: "U heeft het recht op inzage, correctie en verwijdering van uw gegevens.", s5title: "5. Contact", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Gebruiksvoorwaarden", updated: "Laatste update: 14 maart 2026", intro: "Welkom bij bdai. Door de app te gebruiken, gaat u akkoord met deze voorwaarden.", s1title: "1. Gebruik", s1: "U verbindt zich ertoe de app alleen voor wettelijke doeleinden te gebruiken.", s2title: "2. Accounts", s2: "U bent verantwoordelijk voor de vertrouwelijkheid van uw inloggegevens.", s3title: "3. Inhoud", s3: "Door inhoud bij te dragen, verleent u ons een niet-exclusieve wereldwijde licentie.", s4title: "4. Beloningen", s4: "Miles hebben geen werkelijke geldwaarde.", s5title: "5. Contact", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  pl: {
    privacy: { title: "Polityka Prywatności", updated: "Ostatnia aktualizacja: 14 marca 2026", intro: "W bdai szanujemy Twoją prywatność i zobowiązujemy się do ochrony Twoich danych osobowych.", s1title: "1. Zbierane dane", s1: "Zbieramy dane, które nam podajesz: imię, email, wiek, miasto, kraj i język. Zbieramy także dane GPS.", s2title: "2. Wykorzystanie danych", s2: "Używamy Twoich danych do świadczenia i ulepszania naszych usług.", s3title: "3. Udostępnianie danych", s3: "Nie sprzedajemy Twoich danych osobowych osobom trzecim.", s4title: "4. Twoje prawa (RODO)", s4: "Masz prawo dostępu, poprawiania i żądania usunięcia swoich danych.", s5title: "5. Kontakt", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Warunki Użytkowania", updated: "Ostatnia aktualizacja: 14 marca 2026", intro: "Witamy w bdai. Korzystając z aplikacji, akceptujesz niniejsze Warunki.", s1title: "1. Użytkowanie", s1: "Zobowiązujesz się używać aplikacji wyłącznie w celach zgodnych z prawem.", s2title: "2. Konta", s2: "Jesteś odpowiedzialny za poufność swoich danych logowania.", s3title: "3. Treść", s3: "Przesyłając treści, udzielasz nam niewyłącznej, ogólnoświatowej licencji.", s4title: "4. Nagrody", s4: "Mile nie mają rzeczywistej wartości pieniężnej.", s5title: "5. Kontakt", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  ca: {
    privacy: { title: "Política de Privacitat", updated: "Darrera actualització: 14 de març de 2026", intro: "A bdai, respectem la vostra privacitat i ens comprometem a protegir les vostres dades personals.", s1title: "1. Dades recollides", s1: "Recollim les dades que ens proporcioneu: nom, email, edat, ciutat, país i idioma. També recollim dades GPS.", s2title: "2. Ús de les dades", s2: "Usem les vostres dades per proporcionar i millorar els nostres serveis.", s3title: "3. Compartir dades", s3: "No venem les vostres dades personals a tercers.", s4title: "4. Els vostres drets (RGPD)", s4: "Teniu dret a accedir, rectificar i sol·licitar la supressió de les vostres dades.", s5title: "5. Contacte", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Termes d'Ús", updated: "Darrera actualització: 14 de març de 2026", intro: "Benvingut a bdai. En accedir a la nostra app, accepteu aquests Termes.", s1title: "1. Ús", s1: "Us comprometeu a usar l'app només per a fins legals.", s2title: "2. Comptes", s2: "Sou responsables de la confidencialitat de les vostres credencials.", s3title: "3. Contingut", s3: "En contribuir contingut, ens atorgeu una llicència mundial no exclusiva.", s4title: "4. Recompenses", s4: "Les milles no tenen valor monetari real.", s5title: "5. Contacte", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  eu: {
    privacy: { title: "Pribatutasun Politika", updated: "Azken eguneratzea: 2026ko martxoaren 14a", intro: "bdai-n, zure pribatutasuna errespetatzen dugu eta zure datu pertsonalak babesteko konpromisoa hartzen dugu.", s1title: "1. Bildutako datuak", s1: "Zuzenean ematen dizkiguzun datuak biltzen ditugu: izena, emaila, adina, hiria, herrialdea eta hizkuntza. GPS datuak ere biltzen ditugu.", s2title: "2. Datuen erabilera", s2: "Zure datuak gure zerbitzuak eskaintzeko eta hobetzeko erabiltzen ditugu.", s3title: "3. Datuak partekatzea", s3: "Ez ditugu zure datu pertsonalak hirugarrenei saltzen.", s4title: "4. Zure eskubideak (DBEO)", s4: "Zure datuetara sartzeko, zuzentzeko eta ezabatzeko eskubidea duzu.", s5title: "5. Kontaktua", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Erabilera Baldintzak", updated: "Azken eguneratzea: 2026ko martxoaren 14a", intro: "Ongi etorri bdai-ra. App-a erabiliz, baldintza hauek onartzen dituzu.", s1title: "1. Erabilera", s1: "App-a helburu legaletarako bakarrik erabiltzeko konpromisoa hartzen duzu.", s2title: "2. Kontuak", s2: "Zure kredentzialak konfidentzialtasunez gordetzea zure erantzukizuna da.", s3title: "3. Edukia", s3: "Edukia ekarriz, mundu mailako lizentzia ez-esklusiboa ematen diguzue.", s4title: "4. Sariak", s4: "Miliek ez dute diru-balio errealrik.", s5title: "5. Kontaktua", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  vi: {
    privacy: { title: "Chính sách Quyền riêng tư", updated: "Cập nhật lần cuối: 14 tháng 3 năm 2026", intro: "Tại bdai, chúng tôi tôn trọng quyền riêng tư của bạn và cam kết bảo vệ dữ liệu cá nhân của bạn.", s1title: "1. Dữ liệu thu thập", s1: "Chúng tôi thu thập dữ liệu bạn cung cấp trực tiếp: tên, email, tuổi, thành phố, quốc gia và ngôn ngữ. Chúng tôi cũng thu thập dữ liệu GPS.", s2title: "2. Sử dụng dữ liệu", s2: "Chúng tôi sử dụng dữ liệu của bạn để cung cấp và cải thiện dịch vụ.", s3title: "3. Chia sẻ dữ liệu", s3: "Chúng tôi không bán dữ liệu cá nhân của bạn cho bên thứ ba.", s4title: "4. Quyền của bạn (GDPR)", s4: "Bạn có quyền truy cập, chỉnh sửa và yêu cầu xóa dữ liệu của mình.", s5title: "5. Liên hệ", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "Điều khoản Sử dụng", updated: "Cập nhật lần cuối: 14 tháng 3 năm 2026", intro: "Chào mừng đến với bdai. Bằng cách sử dụng ứng dụng, bạn đồng ý với các Điều khoản này.", s1title: "1. Sử dụng", s1: "Bạn cam kết chỉ sử dụng ứng dụng cho các mục đích hợp pháp.", s2title: "2. Tài khoản", s2: "Bạn chịu trách nhiệm về tính bảo mật của thông tin đăng nhập.", s3title: "3. Nội dung", s3: "Bằng cách đóng góp nội dung, bạn cấp cho chúng tôi giấy phép toàn cầu không độc quyền.", s4title: "4. Phần thưởng", s4: "Dặm không có giá trị tiền tệ thực tế.", s5title: "5. Liên hệ", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  },
  th: {
    privacy: { title: "นโยบายความเป็นส่วนตัว", updated: "อัปเดตล่าสุด: 14 มีนาคม 2026", intro: "ที่ bdai เราเคารพความเป็นส่วนตัวของคุณและมุ่งมั่นที่จะปกป้องข้อมูลส่วนบุคคลของคุณ", s1title: "1. ข้อมูลที่เก็บรวบรวม", s1: "เราเก็บรวบรวมข้อมูลที่คุณให้โดยตรง: ชื่อ อีเมล อายุ เมือง ประเทศ และภาษา รวมถึงข้อมูล GPS", s2title: "2. การใช้ข้อมูล", s2: "เราใช้ข้อมูลของคุณเพื่อให้บริการและปรับปรุงบริการของเรา", s3title: "3. การแชร์ข้อมูล", s3: "เราไม่ขายข้อมูลส่วนบุคคลของคุณให้กับบุคคลที่สาม", s4title: "4. สิทธิ์ของคุณ (GDPR)", s4: "คุณมีสิทธิ์เข้าถึง แก้ไข และขอลบข้อมูลของคุณ", s5title: "5. ติดต่อ", s5: "Daysi Chong Zambrano — info@bdai.travel" },
    terms: { title: "ข้อกำหนดการใช้งาน", updated: "อัปเดตล่าสุด: 14 มีนาคม 2026", intro: "ยินดีต้อนรับสู่ bdai การใช้แอปถือว่าคุณยอมรับข้อกำหนดเหล่านี้", s1title: "1. การใช้งาน", s1: "คุณตกลงที่จะใช้แอปเพื่อวัตถุประสงค์ที่ถูกต้องตามกฎหมายเท่านั้น", s2title: "2. บัญชี", s2: "คุณรับผิดชอบต่อการรักษาความลับของข้อมูลเข้าสู่ระบบ", s3title: "3. เนื้อหา", s3: "การมีส่วนร่วมในเนื้อหาถือว่าคุณให้สิทธิ์ใช้งานทั่วโลกแบบไม่ผูกขาด", s4title: "4. รางวัล", s4: "ไมล์ไม่มีมูลค่าทางการเงินที่แท้จริง", s5title: "5. ติดต่อ", s5: "Daysi Chong Zambrano — info@bdai.travel" }
  }
};

const getText = (language: string, type: 'privacy' | 'terms') => {
  return LEGAL_TEXTS[language]?.[type] || LEGAL_TEXTS['en'][type];
};

export const LegalModal: React.FC<LegalModalProps> = ({ type, onClose, language = 'es' }) => {
  const text = getText(language, type);

  return (
    <div className="fixed inset-0 z-[10000] bg-slate-950/98 backdrop-blur-2xl flex flex-col">
      <div className="flex justify-between items-center px-6 pt-12 pb-4 shrink-0">
        <h2 className="text-white font-black text-xl uppercase tracking-widest">{text.title}</h2>
        <button onClick={onClose} className="w-10 h-10 rounded-xl bg-white/10 text-white flex items-center justify-center border border-white/5 active:scale-90 shadow-lg shrink-0">
          <i className="fas fa-times"></i>
        </button>
      </div>
      <div className="flex-1 overflow-y-auto px-6 pb-12">
        <div className="w-full max-w-md mx-auto bg-slate-900 border border-white/10 rounded-3xl p-6 text-slate-300 text-sm leading-relaxed space-y-6">
          <p><strong className="text-white">{text.updated}</strong></p>
          <p>{text.intro}</p>
          <h3 className="text-white font-bold uppercase tracking-widest text-xs pt-2">{text.s1title}</h3>
          <p>{text.s1}</p>
          <h3 className="text-white font-bold uppercase tracking-widest text-xs pt-2">{text.s2title}</h3>
          <p>{text.s2}</p>
          <h3 className="text-white font-bold uppercase tracking-widest text-xs pt-2">{text.s3title}</h3>
          <p>{text.s3}</p>
          <h3 className="text-white font-bold uppercase tracking-widest text-xs pt-2">{text.s4title}</h3>
          <p>{text.s4}</p>
          <h3 className="text-white font-bold uppercase tracking-widest text-xs pt-2">{text.s5title}</h3>
          <p>{text.s5}</p>
          {text.s6title && <>
            <h3 className="text-white font-bold uppercase tracking-widest text-xs pt-2">{text.s6title}</h3>
            <p>{text.s6}</p>
          </>}
        </div>
      </div>
    </div>
  );
};
